#pragma once
#ifndef GLOBAL

#define GLOBAL

#define SCALE 2
#define SPRITESHEET_OFFSET 1
#define SPRITESHEET_CELL_COUNT_PER_ROW 32
#define SPRITESHEET_CELL_SIZE 16
#define FRAME_RATE 144
#define SCREEN_WIDTH 48
#define SCREEN_HEIGHT 24

#define PLAYER_SPEED 0.1

#endif // !GLOBAL
